#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2019, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#

# Top level inventory.
all:

    vars:

        ansible_ssh_user: "{{ lookup('env','ESPERIA_USERNAME') }}"
        ansible_ssh_common_args: "-F {{ lookup('env','HOME') }}/.ssh/esperia-config"

        users:
            dmr:
                sshkey: 'dmr.roe.ac.uk.rsa.pub'

            msh:
                sshkey: 'msh.roe.ac.uk.rsa.pub'

            stv:
                sshkey: 'stv.roe.ac.uk.rsa.pub'

            khaba:
                sshkey: 'khaba.roe.ac.uk.rsa.pub'

            gfrancis:
                sshkey: 'gfrancis.epcc.ed.ac.uk.rsa.pub'

            lssthead:
                sshkey: 'root.lsstukhead.pub'

    hosts:

        lssthead:
            vlaneth: 'enp5s0'
            vlanip4: '172.16.1.11/16'
            ineteth: 'enp4s4f0'
            inetip4: '192.41.108.44/24'
            gateway: '192.41.108.126'
            logins:
                - 'msh'
                - 'dmr'
                - 'stv'
                - 'gfrancis'
            admins:
                - 'msh'
                - 'dmr'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'

        work01:
            vlaneth: 'eno1'
            vlanip4: '172.16.1.1/16'
            macbase: '06:00:AC:10:00'
            ip4base: '172.16.0'
            logins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            admins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Onaukon'
              - 'Kedaessa'
              - 'Arardobwyn'
              - 'Graudia'
              - 'Legiesh'
              - 'Oneawiel'
              - 'Afelav'
              - 'Tiesa'
              - 'Qynwan'
              - 'Grissa'
              - 'Treared'
              - 'Faewien'
              - 'Tienwan'
              - 'Triesa'
              - 'Troath'
              - 'Lareliwiel'
              - 'Iberigan'
              - 'Criressa'
              - 'Adagan'
              - 'Kardoswen'
              - 'Cedrijan'
              - 'Vaelle'
              - 'Ocelisean'
              - 'Araeri'
              - 'Nyderrad'
              - 'Rhoawien'
              - 'Gwirabard'
              - 'Boasien'
              - 'Falidon'
              - 'Brawia'
              - 'Glaubard'
              - 'Legendamwen'

        work02:
            vlaneth: 'eno1'
            vlanip4: '172.16.1.2/16'
            macbase: '06:00:AC:10:02'
            ip4base: '172.16.2'
            logins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            admins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Nydiabaen'
              - 'Eraullan'
              - 'Dwerader'
              - 'Koiclya'
              - 'Afeadon'
              - 'Arieven'
              - 'Yberil'
              - 'Umiwiel'
              - 'Waresean'
              - 'Meng'
              - 'Tromader'
              - 'Haosien'
              - 'Year'
              - 'Glerraswen'
              - 'Gworekin'
              - 'Elaven'
              - 'Ybigorid'
              - 'Ereagord'
              - 'Etherralian'
              - 'Drilawyr'
              - 'Kaaucien'
              - 'Dwiralin'
              - 'Rhaelson'
              - 'Shllips'
              - 'Wafire'
              - 'Owensag'
              - 'Spus'
              - 'Hadelia'
              - 'Anticla'
              - 'Broocal'
              - 'Saunobby'
              - 'Hartatoria'

        work03:
            vlaneth: 'eno1'
            vlanip4: '172.16.1.3/16'
            macbase: '06:00:AC:10:03'
            ip4base: '172.16.3'
            logins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            admins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Umynd'
              - 'Lothaedien'
              - 'Afaod'
              - 'Rhaussa'
              - 'Etiach'
              - 'Ederradda'
              - 'Ethaledric'
              - 'Piramma'
              - 'Weag'
              - 'Adririen'
              - 'Boader'
              - 'Loidda'
              - 'Keriron'
              - 'Wiciavia'
              - 'Galeas'
              - 'Ocaredia'
              - 'Sevardokath'
              - 'Pilima'
              - 'Dwerralath'
              - 'Elardolind'
              - 'Ethaw'
              - 'Sericia'
              - 'Ceihan'
              - 'Glassa'
              - 'Umelakor'
              - 'Galirien'
              - 'Tilader'
              - 'Grywiel'
              - 'Payw'
              - 'Paowien'
              - 'Yorevudd'
              - 'Haaewia'

        work04:
            vlaneth: 'eno1'
            vlanip4: '172.16.1.4/16'
            macbase: '06:00:AC:10:04'
            ip4base: '172.16.4'
            logins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            admins:
                - 'msh'
                - 'dmr'
                - 'gfrancis'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Rhaler'
              - 'Asaoria'
              - 'Miejar'
              - 'Ocerasa'
              - 'Frendakith'
              - 'Cieng'
              - 'Calelath'
              - 'Loreviel'
              - 'Jilam'
              - 'Heraveth'
              - 'Elyth'
              - 'Qirassi'
              - 'Ybib'
              - 'Qardode'
              - 'Vardodric'
              - 'Legianiel'
              - 'Deranyth'
              - 'Wicella'
              - 'Kardoloth'
              - 'Thoedith'
              - 'Nydiratlan'
              - 'Hadith'
              - 'Aeakith'
              - 'Jerywien'
              - 'Joric'
              - 'Nyderradda'
              - 'Oloend'
              - 'Ethewia'
              - 'Afeb'
              - 'Ocianiel'
              - 'Umywin'
              - 'Grywen'

        trop03:
            vlaneth: 'eth1'
            vlanip4: '172.16.1.5/16'
            ineteth: 'eth0'
            inetip4: '129.215.175.98/24'
            gateway: '129.215.175.126'
            macbase: '06:00:AC:10:05'
            ip4base: '172.16.5'
            logins:
                - 'msh'
                - 'dmr'
            admins:
                - 'msh'
                - 'dmr'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Umiawyth'
              - 'Etalema'
              - 'Greand'
              - 'Nydiralle'
              - 'Kedaekoth'
              - 'Onelith'
              - 'Elaleld'
              - 'Afoaviel'
              - 'Rusaldez'
              - 'Stedigo'
              - 'Angece'
              - 'Edwalafia'
              - 'Onoza'
              - 'Fosauri'
              - 'Marpus'
              - 'Byflame'
              - 'Grerat'
              - 'Jeralenia'
              - 'Dwardoa'
              - 'Larohac'
              - 'Kaaeclya'
              - 'Elirannor'
              - 'Jeroaveth'
              - 'Rorekon'
              - 'Astalenna'
              - 'Afib'
              - 'Lotholia'
              - 'Astilamos'
              - 'Uloreth'
              - 'Comwen'
              - 'Etardowyn'
              - 'Legaleniel'

        trop04:
            vlaneth: 'eth1'
            vlanip4: '172.16.1.6/16'
            ineteth: 'eth0'
            inetip4: '129.215.175.99/24'
            gateway: '129.215.175.126'
            macbase: '06:00:AC:10:06'
            ip4base: '172.16.6'
            logins:
                - 'msh'
                - 'dmr'
            admins:
                - 'msh'
                - 'dmr'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Wumar'
              - 'Larilaweth'
              - 'Ror'
              - 'Asterade'
              - 'Ibedrinnon'
              - 'Arigorith'
              - 'Glydan'
              - 'Clarith'
              - 'Cadoired'
              - 'Adweasien'
              - 'Etemar'
              - 'Sevaymwen'
              - 'Rydan'
              - 'Kaaclya'
              - 'Crohab'
              - 'Iberani'
              - 'Nerrawan'
              - 'Gwauswen'
              - 'Cirel'
              - 'Gendaswen'
              - 'Ocede'
              - 'Crilird'
              - 'Astendawen'
              - 'Nendalith'
              - 'Saelia'
              - 'Adwaeric'
              - 'Moemond'
              - 'Iberidia'
              - 'Thelinidd'
              - 'Sendalin'
              - 'Dwalewen'
              - 'Gwoeric'

        lsstukdata1:
            vlaneth: 'eno1'
            vlanip4: '172.16.1.7/16'
            macbase: '06:00:AC:10:07'
            ip4base: '172.16.7'
            inetip4: '192.41.108.45'
            logins:
                - 'msh'
            admins:
                - 'msh'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
            vmnames:
              - 'lsstukdata1-01'
              - 'lsstukdata1-02'
              - 'lsstukdata1-03'
              - 'lsstukdata1-04'

        lsstukdata2:
            vlaneth: 'eno1'
            vlanip4: '172.16.1.8/16'
            macbase: '06:00:AC:10:08'
            ip4base: '172.16.8'
            logins:
                - 'msh'
            admins:
                - 'msh'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
            vmnames:
              - 'lsstukdata2-01'
              - 'lsstukdata2-02'
              - 'lsstukdata2-03'
              - 'lsstukdata2-04'

        gaia01:
            vlaneth: 'enp33s0f0'
            vlanip4: '172.16.1.9/16'
            macbase: '06:00:AC:10:09'
            ip4base: '172.16.9'
            logins:
                - 'msh'
                - 'dmr'
            admins:
                - 'msh'
                - 'dmr'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Cinna'
              - 'Edieldan'
              - 'Adwiraven'
              - 'Craygord'
              - 'Haoniel'
              - 'Moif'
              - 'Asterran'
              - 'Kalec'
              - 'Ocyssa'
              - 'Adwelarin'
              - 'Erardossa'
              - 'Astomar'
              - 'Aciamma'
              - 'Welak'
              - 'Deranna'
              - 'Girelath'
              - 'Adraeswen'
              - 'Birakith'
              - 'Gometh'
              - 'Alauseth'
              - 'Jeremeth'
              - 'Acerawyr'
              - 'Pethiel'
              - 'Oneliwyth'
              - 'Vaeni'
              - 'Elinad'
              - 'Frilicien'
              - 'Herakith'
              - 'Sevimma'
              - 'Gledrili'
              - 'Olalewiel'
              - 'Tralidus'

        gaia02:
            vlaneth: 'enp33s0f0'
            vlanip4: '172.16.1.10/16'
            macbase: '06:00:AC:10:0A'
            ip4base: '172.16.10'
            logins:
                - 'msh'
                - 'dmr'
            admins:
                - 'msh'
                - 'dmr'
            supers:
                - 'lssthead'
                - 'khaba'
                - 'msh'
                - 'dmr'
            vmnames:
              - 'Kaaleder'
              - 'Drardorien'
              - 'Adaokin'
              - 'Larilla'
              - 'Adwoac'
              - 'Ibardocia'
              - 'Glalewyth'
              - 'Crealia'
              - 'Galildan'
              - 'Rheria'
              - 'Gloewyn'
              - 'Miraedith'
              - 'Dumar'
              - 'Adoadien'
              - 'Eroidon'
              - 'Cheithiel'
              - 'Daretlan'
              - 'Heani'
              - 'Chobard'
              - 'Grirewen'
              - 'Wov'
              - 'Sevendani'
              - 'Zireand'
              - 'Griredien'
              - 'Salekoth'
              - 'Sendathien'
              - 'Legurid'
              - 'Cramma'
              - 'Adwaesean'
              - 'Verrasien'
              - 'Walewyn'
              - 'Thelithiel'

    # Child groups
    children:

        # Gateway nodes.
        gateways:
            hosts:
                lssthead:

        # LSST worker nodes (Debian buster/sid).
        lsstnodes:
            hosts:
                work01:
                work02:
                work03:
                work04:

        # LSST data nodes (Debian buster/sid).
        datanodes:
            hosts:
                lsstukdata1:
                lsstukdata2:

        # Gaia worker nodes (Debian buster/sid).
        gaianodes:
            hosts:
                gaia01:
                gaia02:

        # Trop nodes (Debian 9.11).
        tropnodes:
            hosts:
                trop03:
                trop04:

        # List of nodes that need DHCP ranges.
        dhcpnodes:
            hosts:
                work01:
                work02:
                work03:
                work04:
                gaia01:
                gaia02:
                trop03:
                trop04:

        # List of physical VLAN nodes.
        vlannodes:
            hosts:
                work01:
                work02:
                work03:
                work04:
                trop03:
                trop04:
                lsstukdata1:
                lsstukdata2:
                gaia01:
                gaia02:

        # List of external inet nodes.
        inetnodes:
            hosts:
                trop03:
                trop04:
                lsstukdata1:
                lsstukdata2:
                gaia01:
                gaia02:

